name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Ejecución de pruebas unitarias
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest moto boto3

      - name: Ejecutar pruebas con pytest
        run: PYTHONPATH=$(pwd) pytest test/

  deploy:
    name: Despliegue automático en AWS
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v3
      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Verificar credenciales AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1
      - name: Desplegar lambda
        run: |
          # Crear y activar el entorno virtual
          python -m venv venv
          source venv/bin/activate
          
          # Instalar Zappa y boto3
          pip install zappa boto3
          
          # Desplegar Lambda de Scraping
          zappa update devInfo --settings_file punto1/zappa_settings.json
          
          # Desplegar Lambda de Procesamiento
          zappa update dev_csv --settings_file punto2/zappa_settings.json

          # Desplegar Lambda de crawler
          zappa update crawler --settings_file punto3/zappa_settings.json
